=== madeleiine96/Webbteknik/L1/booklist.dtd
<!--
booklist
	genre
	book*
                attr: language (eng/swe/den)
		title
		author+
                        firstName
                        lastName
		publisher
                publishYear
                        attr: edition?
			attr: ISBN
		pageNumber
		plot?
		bookSerie?
			attr: numberInSerie?
		bookcover?
			attr: image
			attr: illustrator?
		buyBook
			attr: url
-->


<!ELEMENT booklist (genre, book*)>
	<!ELEMENT genre (#PCDATA)>
	<!ELEMENT book (title, author+, publisher, publishYear, pageNumber, plot?, bookSerie?, bookcover?, buyBook)>
		<!ATTLIST book language (eng|swe|den) #REQUIRED>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT author (firstName, lastName)>
			<!ELEMENT firstName (#PCDATA)>
			<!ELEMENT lastName (#PCDATA)>
		<!ELEMENT publisher (#PCDATA)>
		<!ELEMENT publishYear (#PCDATA)>
			<!ATTLIST publishYear edition CDATA #IMPLIED ISBN CDATA #REQUIRED>
		<!ELEMENT pageNumber (#PCDATA)>
		<!ELEMENT plot (#PCDATA)>
		<!ELEMENT bookSerie (#PCDATA)>
			<!ATTLIST bookSerie numberInSerie CDATA #IMPLIED>
		<!ELEMENT bookcover EMPTY>
				<!ATTLIST bookcover image CDATA #REQUIRED illustrator CDATA #IMPLIED>
		<!ELEMENT buyBook EMPTY>
				<!ATTLIST buyBook url CDATA #REQUIRED>

=== madeleiine96/Webbteknik/L1/booklist_fantasy.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">


<booklist>

        <genre>Fantasy</genre>

        <book language="eng">

                <title>Harry Potter and the Philosopher's Stone</title>
                <author>
                        <firstName>J.K</firstName>
                        <lastName>Rowling</lastName>
                </author>
                <publisher>Bloomsbury Publishing PLC</publisher>
                <publishYear ISBN="9780747532743">1997</publishYear>
                <pageNumber>224</pageNumber>
                <plot>
                        Harry Potter is an ordinary boy who lives in a cupboard under the stairs at his Aunt Petunia and Uncle Vernon's house, which he thinks is normal for someone like him who's parents have been killed in a 'car crash'. He is bullied by them and his fat, spoilt cousin Dudley, and lives a very unremarkable life with only the odd hiccup (like his hair growing back overnight!) to cause him much to think about. That is until an owl turns up with a letter addressed to Harry and all hell breaks loose! He is literally rescued by a world where nothing is as it seems and magic lessons are the order of the day. Read and find out how Harry discovers his true heritage at Hogwarts School of Wizardry and Witchcraft, the reason behind his parents mysterious death, who is out to kill him, and how he uncovers the most amazing secret of all time, the fabled Philosopher's Stone! All this and muggles too. Now, what are they?
                </plot>
                <bookSerie numberInSerie="1">Harry Potter</bookSerie>
                <bookcover image="pictures/philosophersStone" illustrator="Mary Grandpré" />
                <buyBook url="https://www.alibris.co.uk/search/books/isbn/9780747532743" />
        </book>

        <book language="swe">

                <title>Eld</title>
                <author>
                        <firstName>Mats</firstName>
                        <lastName>Strandberg</lastName>
                </author>
                <author>
                        <firstName>Sara</firstName>
                        <lastName>Bergmark Elfgren</lastName>
                </author>
                <publisher>Rabén &amp; Sjögren</publisher>
                <publishYear edition="1" ISBN="9789129704860">2017</publishYear>
                <pageNumber>638</pageNumber>
                <plot>
                        De utvalda ska börja andra året på gymnasiet. Hela sommarlovet har de hållit andan i väntan på demonernas nästa drag. Men hotet kommer från ett håll de aldrig kunnat förutse. Det blir alltmer uppenbart att något är väldigt, väldigt fel i Engelsfors. Det förflutna vävs ihop med nuet. De levande möter de döda. De utvalda knyts allt tätare till varandra och påminns återigen om att magi inte kan lindra olycklig kärlek eller laga krossade hjärtan.
                </plot>
                <bookSerie numberInSerie="2">Engelsfors-trilogin</bookSerie>
                <bookcover image="pictures/eld" />
                <buyBook url="https://www.adlibris.com/se/bok/eld-9789129704860" />
        </book>


        <book language="eng">

                <title>Harry Potter and the Goblet of Fire</title>
                <author>
                        <firstName>J.K</firstName>
                        <lastName>Rowling</lastName>
                </author>
                <publisher>Bloomsbury Publishing PLC</publisher>
                <publishYear ISBN="9780747550990">2001</publishYear>
                <pageNumber>636</pageNumber>
                <plot>
                        The summer holidays are dragging on and Harry Potter can't wait for the start of the school year. It is his fourth year at Hogwarts School of Witchcraft and Wizardry and there are spells to be learnt and (unluckily) Potions and Divination lessons to be attended. But Harry can't know that the atmosphere is darkening around him, and his worst enemy is preparing a fate that it seems will be inescapable . . .
                </plot>
                <bookSerie numberInSerie="4">Harry Potter</bookSerie>
                <bookcover image="pictures/gobletOfFire" />
                <buyBook url="https://www.abebooks.co.uk/9780747550990/Harry-Potter-Goblet-Fire-Book-0747550999/plp" />
        </book>

        <book language="swe">

                <title>Nyckeln</title>
                <author>
                        <firstName>Mats</firstName>
                        <lastName>Strandberg</lastName>
                </author>
                <author>
                        <firstName>Sara</firstName>
                        <lastName>Bergmark Elfgren</lastName>
                </author>
                <publisher>Rabén &amp; Sjögren</publisher>
                <publishYear edition="1" ISBN="9789129704877">2017</publishYear>
                <pageNumber>818</pageNumber>
                <plot>
                        Det har gått drygt en månad sedan tragedin i Engelsfors gymnasiums gympasal. De utvalda får ingen tid att återhämta sig innan deras värld vänds upp och ner igen. Frågor besvaras. Hemligheter avslöjas. Lojaliteter prövas. Tiden håller på att rinna ut och till slut kan De utvalda bara vara säkra på en sak: Allt kommer att förändras.
                </plot>
                <bookSerie numberInSerie="3">Engelsfors-trilogin</bookSerie>
                <bookcover image="pictures/nyckeln" />
                <buyBook url="https://www.adlibris.com/se/bok/nyckeln-9789129704877" />
        </book>


</booklist>

=== madeleiine96/Webbteknik/L1/booklist_romance.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">


<booklist>

        <genre>Romance</genre>


        <book language="eng">

                <title>The Last Song</title>
                <author>
                        <firstName>Nicholas</firstName>
                        <lastName>Sparks</lastName>
                </author>
                <publisher>Grand Central Publishing</publisher>
                <publishYear ISBN="9780446547567">2009</publishYear>
                <pageNumber>390</pageNumber>
                <plot>
                        Seventeen-year-old Veronica 'Ronnie' Miller's life was turned upside-down when her parents divorced and her father moved from New York City to Wilmington, North Carolina. Three years later, she remains angry and alienated from her parents, especially her father . . . until her mother decides it would be in everyone's best interest if she spent the summer in Wilmington with him. Ronnie's father, a former concert pianist and teacher, is living a quiet life in the beach town, immersed in creating a work of art that will become the centerpiece of a local church.
                </plot>
                <bookcover image="pictures/lastsong" />
                <buyBook url="https://www.abebooks.co.uk/9780446547567/Last-Song-Sparks-Nicholas-0446547565/plp" />
        </book>

        <book language="swe">

                <title>Det slutar med oss</title>
                <author>
                        <firstName>Colleen</firstName>
                        <lastName>Hoover</lastName>
                </author>
                <publisher>Lovereads</publisher>
                <publishYear ISBN="9789188803719">2009</publishYear>
                <pageNumber>409</pageNumber>
                <plot>
                        Lily har inte alltid haft det lätt och varit tvungen att jobba hårt för det liv hon vill ha. Det har varit en lång resa från uppväxten i Maine – hon har gått ut college, flyttat till Boston och fullföljt sin dröm om att öppna en egen blomsterhandel. Så när hon och den ursnygge neurokirurgen Ryle förälskar sig i varandra verkar Lilys liv nästan för bra för att vara sant.

                        Ryle är känslig, intelligent och väldigt svag för Lily. Men han är också självsäker, envis och kanske till och med lite arrogant. När Lily tvingas ifrågasätta sitt förhållande med Ryle börjar hon också tänka på Atlas. Han var hennes första kärlek och en viktig länk till hennes förflutna. När han plötsligt dyker upp i hennes liv igen, hotas allt Lily byggt upp med Ryle.
                </plot>
                <bookcover image="pictures/slutar_med_oss" illustrator="Miroslav Sokcic" />
                <buyBook url="https://www.adlibris.com/se/bok/det-slutar-med-oss-9789188803719" />
        </book>

        <book language="den">

                <title>Romantiske haver</title>
                <author>
                        <firstName>Claus</firstName>
                        <lastName>Dalby</lastName>
                </author>
                <publisher>Klematis</publisher>
                <publishYear edition="1" ISBN="9788771391251">2015</publishYear>
                <pageNumber>396</pageNumber>
                <plot>
                        Mange drømmer om at skabe en romantisk have. Denne bog viser, hvordan en række mennesker har gjort drømmen til virkelighed. Claus Dalby har gennem flere sæsoner besøgt og fotograferet spændende og romantiske haver i Frankrig, Belgien, Holland, England og Skandinavien. Til trods for den store geografiske spredning er der masser af inspiration at hente for danske haveejere. Bogen er samtidig en hyldest til roserne, som har en fremtrædende plads i mange af de skønne haver.
                </plot>
                <bookcover image="pictures/romantiskeHaver" />
                <buyBook url="https://www.adlibris.com/se/bok/romantiske-haver-9788771391251" />
        </book>

        <book language="swe">

                <title>Att välja den rätte </title>
                <author>
                        <firstName>Jill</firstName>
                        <lastName>Mansell</lastName>
                </author>
                <publisher>Lovereads</publisher>
                <publishYear ISBN="9789189357730">2022</publishYear>
                <pageNumber>443</pageNumber>
                <plot>
                        Det är inte kärlek Lottie Carlyle är ute efter när hon träffar sin nya chef, Tyler Klein. Hon är nöjd med sitt lugna liv som det är: med det vackra huset i en idyllisk by på engelska landsbygden, med sina – oftast – väluppfostrade barn och den vänskapliga relationen till sin charmige men slarvige ex-make. Men Tyler visar sig vara helt perfekt för Lottie. Som i sagorna ungefär. Snart har hon fallit för honom, och han för henne. Men ändå kan de inte börja leva lyckliga i alla sina dagar.

                        Lotties barn avskyr nämligen Tyler. Och när charmören Seb visar intresse för henne blir barnen tokiga i honom istället. Lottie blir förvirrad; det är svårt att värja sig mot Seb, men samtidigt är han ju inte Tyler.

                        Och kanske är han inte ens den han utger sig för att vara?
                </plot>
                <bookSerie numberInSerie="4">Kärlek i Cornwall &amp; Cotswolds</bookSerie>
                <bookcover image="pictures/valjaDenRatte" />
                <buyBook url="https://www.adlibris.com/se/bok/att-valja-den-ratte-9789189357730" />
        </book>


</booklist>

=== madeleiine96/Webbteknik/L1/booklist_non_fiction.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE booklist SYSTEM "booklist.dtd">

<booklist>

        <genre>Non-fiction</genre>


        <book language="eng">

                <title>Ultimate guide to optimizing your Website</title>
                <author>
                        <firstName>Jon</firstName>
                        <lastName>Rognerud</lastName>
                </author>
                <publisher>Entrepreneur Press</publisher>
                <publishYear edition="3" ISBN="9781599185200">2014</publishYear>
                <pageNumber>320</pageNumber>
                <plot>
                        Written for beginners, author Jon Rognerud offers a solid introduction to keyword research and competitive analysis, to marketing and messaging, content development, link building, and conversions and tracking of search engine positions. Local search, social media, and blogging are new to this edition, and show examples on how to optimize these important new development areas.  Updated content includes social media search content that reflects strategies and market information to helps business owners easily add this companion to SEO work, blog optimization steps with best SEO tactics for creating search engine friendly sites, and the top ten hottest WordPress plugins for top traffic boost. A local SEO section shows readers how to avoid the most common mistakes on optimizing for local search and the updated section on Google analytics shows how to track top keywords and pages. An updated link building section provides new white hat SEO link building tactics to provide better long term rankings and traffic building, and an expanded resource section includes updated screen-shots of SEO applied. Step-by-step examples are written with an at the kitchen table type dialogue for accessibility and an advanced strategy section takes readers to the next level.
                </plot>
                <bookSerie>Ultimate guide to</bookSerie>
                <bookcover image="pictures/optimizeWebsite" />
                <buyBook url="https://www.amazon.co.uk/Ultimate-Guide-Optimizing-Your-Website/dp/1599185202" />
        </book>

        <book language="swe">

                <title>Effektiv visuell kommunikation : om nyheter, reklam, information och identitet i vår visuella kultur</title>
                <author>
                        <firstName>Bo</firstName>
                        <lastName>Bergström</lastName>
                </author>
                <publisher>Carlsson</publisher>
                <publishYear edition="12" ISBN="9789189063693">2021</publishYear>
                <pageNumber>267</pageNumber>
                <plot>
                        En värld utan bilder, filmer, texter, former och färger är svårt att tänka sig. Lika svårt är det att bortse från de budskap dessa förmedlar. Denna fack- och kursbok, Effektiv visuell kommunikation, ger en övergripande bild av den visuella världen för de professionella kommunikatörerna och studenterna väg in i den. Oavsett om branscherna är nyhetsförmedling, reklam eller information.

                        Men boken tydliggör även effekten av de kommunikativa satsningarna. Ofta blir artikeln läst och affischen styr rakt in i hjärtat - men inte alltid. Vad avgör? Femton kapitel förklarar detta med hjälp av teori, tillämpning, exempel och framför allt inspiration.
                </plot>
                <bookcover image="pictures/effektivVisuellKommunikation" />
                <buyBook url="https://www.adlibris.com/se/bok/effektiv-visuell-kommunikation-om-nyheter-reklam-information-och-identitet-i-var-visuella-kultur-9789189063693" />
        </book>

        <book language="swe">

                <title>Medieetik : framväxt, funktion, framtid </title>
                <author>
                        <firstName>Torbjörn</firstName>
                        <lastName>von Krogh</lastName>
                </author>
                <publisher>Studentlitteratur AB</publisher>
                <publishYear edition="1" ISBN="9789144103891">2016</publishYear>
                <pageNumber>290</pageNumber>
                <plot>
                        Medieetik är både ett sätt att resonera om och ta ansvar för publicistiskt innehåll i medier och olika reglerade fast frivilliga sätt att utkräva ansvar. Självsaneringen tillkom för att stärka ansvarig journalistik, befästa yrkets ställning, bemöta kritik och förhindra en inskränkande lagstiftning.
                        Boken ger en bred överblick av medieetikens område och författaren ställer frågor som:
                        • Vad innebär en etiskt ansvarig hållning från mediernas sida?
                        • Kan en etisk journalist vara konsekvensneutral?
                        • Vad påverkar medieetiken och hur har den vuxit fram?
                        • Har etiken någon framtid när medierna förändras?
                </plot>
                <bookcover image="pictures/medieetik" />
                <buyBook url="https://www.adlibris.com/se/bok/medieetik-framvaxt-funktion-framtid-9789144103891" />
        </book>

        <book language="eng">

                <title>Strategic Communication</title>
                <author>
                        <firstName>Jesper</firstName>
                        <lastName>Falkheimer</lastName>
                </author>
                <author>
                        <firstName>Mats</firstName>
                        <lastName>Heide</lastName>
                </author>
                <publisher>Routledge</publisher>
                <publishYear ISBN="9781138657038">2018</publishYear>
                <pageNumber>160</pageNumber>
                <plot>
                        Strategic communication comprises different forms of goal-oriented communication inside and between organizations, their stakeholders and the society. Strategic communication is an emerging practice and research field integrating established disciplines such as public relations, organizational communication and marketing communication into a holistic framework. The field is based on an awareness of the fundamental importance of communication for the existence and performance of all organizations.
                </plot>
                <bookcover image="pictures/strategicCommunication" />
                <buyBook url="https://www.adlibris.com/se/bok/strategic-communication-9781138657038" />
        </book>

</booklist>
